---
title: "git_01"
author: "Tattiana Rinkenberger"
date: "06/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

When midnight mists are creeping,  
And all the land is sleeping,  
Around me tread the mighty dead,  
And slowly pass away.  
Lo, warriors, saints, and sages,  
From out the vanished ages,  
With solemn pace and reverend face  
Appear and pass away.  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,    
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,    
Shining with all his might:    
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Kindness glides about my house.  
Dame Kindness, she is so nice!  
The blue and red jewels of her rings smoke  
In the windows, the mirrors  
Are filling with smiles.  

What is so real as the cry of a child?    
A rabbit’s cry may be wilder  
But it has no soul.  
Sugar can cure everything, so Kindness says.  
Sugar is a necessary fluid,  

Its crystals a little poultice.  
O kindness, kindness  
Sweetly picking up pieces!  
My Japanese silks, desperate butterflies,  
May be pinned any minute, anesthetized.  

And here you come, with a cup of tea  
Wreathed in steam.  
The blood jet is poetry,  
There is no stopping it.  
You hand me two children, two roses.  